AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - vendor/**/*
Rails:
  Enabled: true
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20
Metrics/AbcSize:
  Max: 100
Metrics/MethodLength:
  CountComments: false
  Max: 30
Metrics/ClassLength:
  CountComments: false
  Max: 1000
BlockNesting:
  Max: 5
Style/BlockDelimiters:
  Enabled: false
Style/MultilineBlockLayout :
  Enabled: true
Style/Documentation:
  Enabled: false
Metrics/ParameterLists:
  Max: 7
  CountKeywordArgs: true
LineLength:
  Enabled: false